export enum CheckFailedReason {
  CornersNotAdjacent = "CORNERS_NOT_ADJACENT",
  EdgeOccupied = "EDGE_OCCUPIED",
  DisconnectedEdge = "DISCONNECTED_EDGE",
  DisconnectedCorner = "DISCONNECTED_CORNER",
  CornerOccupiedByOtherPlayer = "CORNER_OCCUPIED_BY_OTHER_PLAYER",
  CornerOccupied = "CORNER_OCCUPIED",
  CornerAdjacentToOccupiedCorner = "CORNER_ADJACENT_TO_OCCUPIED_CORNER",
  CornerWithoutSettlement = "CORNER_WITHOUT_SETTLEMENT",
  ThiefIsAlreadyInTile = "THIEF_IS_ALREADY_IN_TILE",
  PlayerCantStealFromThemselves = "PLAYER_CANT_STEAL_FROM_THEMSELVES",
  CannotStealFromThatPlayer = "CANNOT_STEAL_FROM_THAT_PLAYER",
  MustStealFromSomePlayer = "MUST_STEAL_FROM_SOME_PLAYER",
  CardAlreadyPlayed = "CARD_ALREADY_PLAYED",
  CardHasNoHolder = "CARD_HAS_NO_HOLDER",
  CardDrawnInThisTurn = "CARD_DRAWN_IN_THIS_TURN",
  UndefinedDestinyTile = "UNDEFINED_DESTINY_TILE",
  UndefinedMonopolyResource = "UNDEFINED_MONOPOLY_RESOURCE",
  UndefinedRoadBuildingCorners = "UNDEFINED_ROAD_BUILDING_CORNERS",
  VictoryPointCardIsNotPlayable = "VICTORY_POINT_CARD_IS_NOT_PLAYABLE",
  UndefinedYearOfPlentyResources = "UNDEFINED_YEAR_OF_PLENTY_RESOURCES",
  EmptyDeck = "EMPTY_DECK",
  NotEnoughResources = "NOT_ENOUGH_RESOURCES",
  SameOriginAndDestinyPlayer = "SAME_ORIGIN_AND_DESTINY_PLAYER",
  NoResourcesGiven = "NO_RESOURCES_GIVEN",
  NoResourcesTaken = "NO_RESOURCES_TAKEN",
  DestinyPlayerNotEnoughResources = "DESTINY_PLAYER_NOT_ENOUGH_RESOURCES",
  CardNotOwnedByPlayer = "CARD_NOT_OWNED_BY_PLAYER",
  RoadAlreadyBuilt = "ROAD_ALREADY_BUILT",
  SettlementNotBuilt = "SETTLEMENT_NOT_BUILT",
  RoadAndSettlementNotAdjacent = "ROAD_AND_SETTLEMENT_NOT_ADJACENT",
  SettlementAlreadyBuilt = "SETTLEMENT_ALREADY_BUILT",
  RoadNotBuilt = "ROAD_NOT_BUILT",
  NotAllowedInThisTurn = "NOT_ALLOWED_IN_THIS_TURN",
  DiceAlreadyRolled = "DICE_ALREADY_ROLLED",
  ResourcesNotAvailable = "RESOURCES_NOT_AVAILABLE",
  ResourcesNotDiscardable = "RESOURCES_NOT_DISCARDABLE",
  DiceRollIsNot7 = "DICE_ROLL_IS_NOT_7",
  ThiefAlreadyMoved = "THIEF_ALREADY_MOVED",
  DiceNotRolled = "DICE_NOT_ROLLED",
  ResourcesNotDiscarded = "RESOURCES_NOT_DISCARDED",
  ThiefNotMoved = "THIEF_NOT_MOVED",
  TurnFinished = "TURN_FINISHED",
  OtherPlayersTurn = "OTHER_PLAYERS_TURN",
  DevelopmentCardAlreadyPlayedInTurn = "DEVELOPMENT_CARD_ALREADY_PLAYED_IN_TURN",
}

export class CheckFailedError extends Error {}
